### ISSUE TITLE
mendix.lang.nullExec causes 'deprecated' messages

### ISSUE THREAD

**Issue by KarinGuldemond** [rik-bos/SetAttribute#4]
Could you please include a replacement for mendix.lang.nullExec in the next version? Thanks!

**Comment by rik-bos** [comment]
Hi Karin,

I just submitted version 2.0.0. This will fix your issue.

In the mean time you could use the version from the latest release (https://github.com/rik-bos/SetAttribute/releases/tag/2.0.0)

Kind regards,
Rik Bos
